theme: jekyll-theme-cayman
title: Bernard Onyango
description: >-
  Welcome to my GitHub Pages site! Here, you'll find my projects, technical skills, 
  and contributions to open-source development.
github:
  is_project_page: false
show_downloads: true
